hbranches:
  only:
    - develop
    - master

language: go
sudo: false
go: 1.7
cache:
  directories:
  - /node_modules

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install v6.9.0
  - nvm use v6.9.0

install:
  - npm install -g gulp@next
  - curl -sSL https://github.com/gohugoio/hugo/releases/download/v0.25.1/hugo_0.25.1_Linux-64bit.tar.gz | tar -zxf - -C /tmp/
  - export PATH="/tmp:$PATH"
  - npm install

script:
  - if [ "$TRAVIS_BRANCH" == "vamp-ee" ]; then gulp build:staging && gulp hugo:vamp-ee-staging; fi
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then gulp build:staging && gulp hugo:staging; fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then gulp build:prod && gulp hugo:prod; fi

# Set correct robots.txt and CNAME files

before_deploy: |
  if [ $TRAVIS_BRANCH == "master" ]; then
    cp ./CNAME ./public/CNAME && cp ./robots.prod.txt ./public/robots.txt
  else
    cp ./robots.dev.txt ./public/robots.txt
  fi

# Deploy master to Github

deploy:
  - provider: pages
    local_dir: public
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: staging.vamp.io
    region: eu-central-1
    local_dir: public
    skip_cleanup: true
    on:
      branch: develop
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: vamp-ee-staging.vamp.io
    region: eu-central-1
    local_dir: public
    skip_cleanup: true
    on:
      branch: vamp-ee

after_deploy:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then curl -X DELETE "https://api.cloudflare.com/client/v4/zones/d398c5b6e2d191e2d6865081facab63b/purge_cache" -H "X-Auth-Email:$CLOUDFLARE_USER" -H "X-Auth-Key:$CLOUDFLARE_KEY" -H "Content-Type:application/json" --data '{"purge_everything":true}'; fi

