[build]
  command = "gulp build:prod && gulp hugo:prod"
  publish = "public"
[context.production.environment]
  HUGO_VERSION = "0.52"

[[redirects]]
  from = "/blog/"
  to = "https://blog.vamp.io/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/schrodingers-canary/"
  to = "https://blog.vamp.io/schrodingers-canary/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/everything-a-machine/"
  to = https://blog.vamp.io/everything-a-machine-automate-ci-cd-to-bend-even-when-code-breaks/
  status = 301
  force = true
